repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types:
          - python
      - id: isort
        name: isort
        entry: isort
        language: system
        types:
          - python
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types:
          - python
        require_serial: true
        args:
          - "--in-place"
          - "--expand-star-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
          - "--remove-all-unused-imports"
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types:
          - python
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types:
          - python
